language: node_js
node_js:
  - "8.2.1"

notifications:
  email:
    recipients:
      - anthonyklinga@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - newman run tests/Oanda.postman_collection.json -e tests/"Oanda - Demo.postman_environment.json"
